### ISSUE TITLE
Folder/File Names are inconsistent

### ISSUE THREAD

**Issue by chrzrdx** [Abhi135721/Code-Addiction#1]
Sometimes, they have spaces ("kth row ..." in the Arrays module), other times they have underscores.

They have to look like this. Please be consistent with the suggested style. No underscores, please.

*CORRECT:*
`InterviewBit/BinarySearch/MedianOfArray/DSP.java`

*INCORRECT:*
`interviewBit/Math/Excel_Column_Number/Excel_Column_Number_dsp.java`

Please fix this ASAP.

**Comment by Abhi135721** [comment]
Ok sir.We will change as early as possible

**Comment by Abhi135721** [comment]
Changed all the folder names as mentioned Sir.
